// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Calendar1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_timeLBL;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_hum;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_wind;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_max;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_first;
extern lv_obj_t * ui_second;
extern lv_obj_t * ui_third;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_forth;
extern lv_obj_t * ui_fift;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_download_png);    // assets\download.png
LV_IMG_DECLARE(ui_img_1294638576);    // assets\openweather-logo-3CE20F48B5-seeklogo.com.png

LV_FONT_DECLARE(ui_font_jedinica);
LV_FONT_DECLARE(ui_font_large);
LV_FONT_DECLARE(ui_font_med);
LV_FONT_DECLARE(ui_font_small);
LV_FONT_DECLARE(ui_font_values);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
